services:
  psql:
    build: ./database
    volumes:
      - data:/var/lib/postgresql/data
  server:
    build: ./server
    ports:
      - 8090:8080
    depends_on:
      - psql
  client:
    build: ./client
    ports:
      - 8080:8081
    depends_on:
      - psql
      - server
  prometheus:
    image: bitnami/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./provisioning:/etc/grafana/provisioning
volumes:
  data:
networks:
  coffee: