apiVersion: apps/v1
kind: Deployment
metadata:
  name: psql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: psql
  template:
    metadata:
      labels:
        app: psql
    spec:
      containers:
        - name: psql-container
          imagePullPolicy: Never
          image: coffee-rest-psql
          env:
            - name: POSTGRES_DB
              value: coffee_db
            - name: POSTGRES_PASSWORD
              value: izpodvipodverta
          ports:
            - containerPort: 5432