apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server-container
          imagePullPolicy: Never
          image: coffee-rest-server
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              port: 8080
            initialDelaySeconds: 5