server:
  port: 8081
spring:
  #  security:
  #    user:
  #      name: test
  #      password: test
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
server-back:
  address: http://localhost:8080